In [92]:
import pandas as pd

In [93]:
df = pd.read_csv('data.csv')

In [75]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0    100         1   67          1           0              1
1    102         0   28          0           0              0
2    100         1   16          0           0              0
3     98         1    1          0           1              1
4     99         1    0          0           0              0

In [76]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
955    102         0   28          0           0              0
956    100         1   16          0           0              0
957     98         1    1          0           1              1
958     99         1    0          0           0              0
959    101         1    1          1           1              1

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fever          960 non-null    int64
 1   bodyPain       960 non-null    int64
 2   age            960 non-null    int64
 3   runnyNose      960 non-null    int64
 4   diffBreath     960 non-null    int64
 5   infectionProb  960 non-null    int64
dtypes: int64(6)
memory usage: 45.1 KB


In [78]:
df['fever'].value_counts()

100    320
102    160
101    160
99     160
98     160
Name: fever, dtype: int64

In [44]:
df['bodyPain'].value_counts()


1    5
0    1
Name: bodyPain, dtype: int64

In [15]:
df.describe()

fever  bodyPain         age  runnyNose  diffBreath  infectionProb
count    6.000000   6.000000   6.000000   6.000000    6.000000       6.000000
mean   100.000000   0.833333  18.833333   0.333333    0.333333       0.500000
std      1.414214   0.408248  26.087673   0.516398    0.516398       0.547723
min     98.000000   0.000000   0.000000   0.000000    0.000000       0.000000
25%     99.250000   1.000000   1.000000   0.000000    0.000000       0.000000
50%    100.000000   1.000000   8.500000   0.000000    0.000000       0.500000
75%    100.750000   1.000000  25.000000   0.750000    0.750000       1.000000
max    102.000000   1.000000  67.000000   1.000000    1.000000       1.000000

In [16]:
 ## Train Test splitting

In [94]:
import numpy as np


In [95]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [96]:
np.random.permutation(7)

array([5, 6, 0, 3, 4, 2, 1])

In [97]:
train,test = data_split(df,0.2)

In [87]:
train

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
302    100         1   16          0           0              0
467    101         1    1          1           1              1
294    100         1   67          1           0              1
548    100         1   16          0           0              0
465     98         1    1          0           1              1
..     ...       ...  ...        ...         ...            ...
106     99         1    0          0           0              0
270    100         1   67          1           0              1
860    100         1   16          0           0              0
435     98         1    1          0           1              1
102    100         1   67          1           0              1

[768 rows x 6 columns]

In [88]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
836    100         1   16          0           0              0
477     98         1    1          0           1              1
350    100         1   16          0           0              0
893    101         1    1          1           1              1
923    101         1    1          1           1              1
..     ...       ...  ...        ...         ...            ...
462    100         1   67          1           0              1
673    102         0   28          0           0              0
33      98         1    1          0           1              1
31     102         0   28          0           0              0
714    100         1   67          1           0              1

[192 rows x 6 columns]

In [84]:
train.index



Int64Index([302, 467, 294, 548, 465, 109,  77, 754, 259,  82,
            ...
            121, 614,  20, 700,  71, 106, 270, 860, 435, 102],
           dtype='int64', length=768)

In [83]:
test.index

Int64Index([836, 477, 350, 893, 923, 261, 215, 334,  86, 878,
            ...
            739, 866, 554, 312, 954, 462, 673,  33,  31, 714],
           dtype='int64', length=192)

In [98]:
#converting dataframe to numpy array
#selecting only features
X_train = train[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()
X_test = test[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()

In [82]:
X_train

array([[102,   0,  28,   0,   0],
       [101,   1,   1,   1,   1],
       [100,   1,  16,   0,   0],
       [ 99,   1,   0,   0,   0],
       [ 98,   1,   1,   0,   1]], dtype=int64)

In [99]:
Y_train = train[['infectionProb']].to_numpy().reshape(768 ,)
Y_test = test[['infectionProb']].to_numpy().reshape(192 ,)

In [62]:
Y_train

array([[0],
       [1],
       [0],
       [0],
       [1]], dtype=int64)

In [50]:
df['bodyPain'].value_counts()

1    5
0    1
Name: bodyPain, dtype: int64

In [53]:
X_train 

array([[102,   0,  28,   0,   0],
       [101,   1,   1,   1,   1],
       [100,   1,  16,   0,   0],
       [ 99,   1,   0,   0,   0],
       [ 98,   1,   1,   0,   1]], dtype=int64)

In [58]:
from sklearn.linear_model import LogisticRegression

In [101]:
clf = LogisticRegression()
clf.fit(X_train,Y_train)

LogisticRegression()

In [106]:
infProb=clf.predict_proba([[100,1,22,-1,1]])[0][1]

In [107]:
infProb

0.30096457726799636